anchor_version = "0.25.0"

[provider]
cluster = "localnet"
wallet = "../config/id.json"

[programs.mainnet]
serum_multisig = "DFXztZTbZzd5NQjRGzvQUL5ZJCoAo7ZdGJcpM4ipG7bA"

[programs.devnet]
serum_multisig = "DFXztZTbZzd5NQjRGzvQUL5ZJCoAo7ZdGJcpM4ipG7bA"

[programs.localnet]
serum_multisig = "DFXztZTbZzd5NQjRGzvQUL5ZJCoAo7ZdGJcpM4ipG7bA"

[scripts]
test = "npx mocha -t 1000000 tests/"
